---
name: "deploy"

on:
  push:
    branches:
      - trunk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: "trunk"
          git_remote_url: "ssh://dokku@news.vinc.cc:22/news"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
